### ISSUE TITLE
클라이언트에서 파일 다운 받을 시 프로그램 종료되는 현상

### ISSUE THREAD

**Issue by kjm99d** [kjm99d/LANShare#2]
**클라이언트에서 파일 다운 받을 시 프로그램 종료되는 현상**

서버로 부터 패킷을 받아 파일을 생성 할 때 죽는다.
파일 저장 시 디렉토리 경로가 존재하지 않아 발생함.

**Comment by oauch** [comment]
죽이지마요 😥
아파요
